"""把 logs/eval_<dataset>_<seed>.txt 收集成一份 CSV。

   python collect_metrics.py              印出表格
   python collect_metrics.py --csv        輸出 CSV 到 stdout
   python collect_metrics.py --csv > damnets_metrics.csv

每個評估檔內含四個模型（DYMOND / AGE / DAMNET / TagGen）各五項指標。
"""
import argparse
import csv
import glob
import os
import re
import sys

MODELS = ["DAMNET", "AGE", "TagGen", "DYMOND"]
METRICS = [
    ("degree_mmd", r"Average degree MMD in data generated by {m}: (.+)"),
    ("clustering_mmd", r"Average clustering MMD in data generated by {m}: (.+)"),
    ("spectral_mmd", r"Average spectral MMD in data generated by {m}: (.+)"),
    ("node_behavior_ks", r"Node behavior KS in data generated by {m}: (.+)"),
    ("random_walk_ks", r"Random walk KS in data generated by {m}: (.+)"),
]


def parse(path):
    text = open(path, encoding="utf-8", errors="replace").read()
    base = os.path.basename(path)[len("eval_"):-len(".txt")]
    dataset, _, seed = base.rpartition("_")
    rows = []
    for m in MODELS:
        row = {"dataset": dataset, "seed": seed, "model": m}
        found = False
        for key, pat in METRICS:
            hit = re.search(pat.format(m=m), text)
            if hit:
                v = hit.group(1).strip()
                row[key] = v
                found = True
            else:
                row[key] = ""
        if found:
            rows.append(row)
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", action="store_true")
    ap.add_argument("--logdir", default=os.path.expanduser("~/DAMNETS_ICML_2022/logs"))
    args = ap.parse_args()

    files = sorted(glob.glob(os.path.join(args.logdir, "eval_*.txt")))
    if not files:
        print("[WARN] {} 底下沒有 eval_*.txt".format(args.logdir), file=sys.stderr)
        return 0

    rows = []
    for f in files:
        got = parse(f)
        if not got:
            print("[WARN] {} 沒有解析到任何指標（可能尚未跑完）".format(os.path.basename(f)),
                  file=sys.stderr)
        rows.extend(got)

    cols = ["dataset", "seed", "model"] + [k for k, _ in METRICS]

    if args.csv:
        w = csv.DictWriter(sys.stdout, fieldnames=cols, lineterminator="\n")
        w.writeheader()
        w.writerows(rows)
    else:
        widths = {c: max(len(c), *(len(str(r.get(c, ""))) for r in rows)) for c in cols}
        print("  ".join(c.ljust(widths[c]) for c in cols))
        print("  ".join("-" * widths[c] for c in cols))
        for r in rows:
            print("  ".join(str(r.get(c, "")).ljust(widths[c]) for c in cols))

    print("\n[INFO] {} 個評估檔，{} 列".format(len(files), len(rows)), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
